-- V2 starter schema for Supabase
create table profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text, currency text default '$', created_at timestamptz default now());
create table loans(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,name text not null,balance numeric(14,2) default 0,emi numeric(14,2) default 0,interest_rate numeric(8,4),created_at timestamptz default now());
create table chits(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,name text not null,monthly numeric(14,2) default 0,months_remaining integer default 0,created_at timestamptz default now());
create table temporary_debts(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,name text not null,original_amount numeric(14,2) default 0,balance numeric(14,2) default 0,created_at timestamptz default now());
create table transactions(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,kind text not null,reference_id bigint,amount numeric(14,2) default 0,note text,occurred_at timestamptz default now());
alter table profiles enable row level security;
alter table loans enable row level security;
alter table chits enable row level security;
alter table temporary_debts enable row level security;
alter table transactions enable row level security;
create policy "own profile" on profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "own loans" on loans for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own chits" on chits for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own temp debts" on temporary_debts for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own transactions" on transactions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
